{% set version = "1.1.2" %}

package:
  name: sixs
  version: {{ version }}

source:
  url: https://bitbucket.org/petebunting/6s/downloads/sixs-{{ version }}.tar.gz
  sha256: 499559146199471fee99eff0ed603ecb0f7d7cf5a0011436edfcb969d641d683
  patches:
      - no_ffpe-summary.patch  # [osx]

build:
  number: 2

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('cxx') }}            # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
  run:
    - m2w64-gcc-libgfortran  # [win]

test:
  files:
  - Example_In_1.txt
  - Example_In_3.txt

about:
  home: https://bitbucket.org/petebunting/6s
  summary: A basic RT code used for atmospheric correction & atmospheric
    simulations
  license: MIT
  # https://bitbucket.org/petebunting/6s/issues/1/no-license-information-and-no-license-file
  # license_file: 
  license_family: MIT
  description:  |
    The 6S code is a basic RT code used for calculation of lookup
    tables in the MODIS atmospheric correction algorithm.
    It enables accurate simulations of satellite and plane observation,
    accounting for elevated targets, use of anisotropic and lambertian surfaces
    and calculation of gaseous absorption. 6S website is http://6s.ltdri.org.

extra:
  recipe-maintainers:
    - robintw
    - danclewley
